# Generated by rust2rpm 27
%bcond check 0

# prevent library files from being installed
%global cargo_install_lib 0
%global forgeurl https://github.com/twosigma/nsncd

Name:           nsncd
Version:        1.4.1

%forgemeta
Release:        %autorelease
Summary:        Name service non-caching daemon

SourceLicense:  Apache-2.0
License:        Unlicense

URL:            %{forgeurl}
Source:         %{forgesource}

BuildRequires:  cargo-rpm-macros >= 26, systemd-rpm-macros

%global _description %{expand:
The name service non-caching daemon.}

%description %{_description}

%prep
%forgeautosetup
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/nsncd
nsncd.service %{_unitdir}/nsncd.service

%changelog
%autochangelog
